# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
install: pip install -r requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/app"
  - export FLASK_DEBUG=1
  - cp config/test_env_config.py config.py
  - cp sample_run.sh run.sh
  - chmod +x run.sh

script:
    - black --check $TRAVIS_BUILD_DIR
    - ./run.sh & pytest

